"""
SQLAlchemy database models for Polymarket arbitrage bot.

This module defines all database tables including markets, trades, positions,
signals, and time-series data for price monitoring.
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    Index,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

Base = declarative_base()


# ==========================================
# Markets & Market Data
# ==========================================

class Market(Base):
    """Polymarket 15-minute BTC up/down markets."""

    __tablename__ = "markets"

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_id = Column(String(100), unique=True, nullable=False, index=True)
    question = Column(Text, nullable=False)
    market_type = Column(String(50))  # 'btc_15min_up_down'
    open_time = Column(DateTime(timezone=True), nullable=False, index=True)
    close_time = Column(DateTime(timezone=True), nullable=False)
    resolution_time = Column(DateTime(timezone=True))
    status = Column(String(20), index=True)  # 'active', 'closed', 'resolved'
    winning_outcome = Column(String(10))  # 'YES', 'NO'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    signals = relationship("Signal", back_populates="market")
    orders = relationship("Order", back_populates="market")
    trades = relationship("Trade", back_populates="market")
    positions = relationship("Position", back_populates="market")


class MarketData(Base):
    """Time-series price data from CEXs (Binance, Coinbase)."""

    __tablename__ = "market_data"

    time = Column(DateTime(timezone=True), primary_key=True, nullable=False)
    exchange = Column(String(20), primary_key=True, nullable=False)  # 'binance', 'coinbase'
    symbol = Column(String(20), primary_key=True, nullable=False)  # 'BTC/USDT'
    price = Column(Numeric(20, 8), nullable=False)
    volume = Column(Numeric(20, 8))

    __table_args__ = (
        Index('idx_market_data_time_exchange', 'time', 'exchange'),
    )


class PolymarketOrderbook(Base):
    """Polymarket orderbook snapshots for YES/NO outcomes."""

    __tablename__ = "polymarket_orderbook"

    time = Column(DateTime(timezone=True), primary_key=True, nullable=False)
    market_id = Column(String(100), primary_key=True, nullable=False)
    outcome = Column(String(10), primary_key=True, nullable=False)  # 'YES', 'NO'
    best_bid = Column(Numeric(10, 4))
    best_ask = Column(Numeric(10, 4))
    bid_size = Column(Numeric(20, 2))
    ask_size = Column(Numeric(20, 2))
    mid_price = Column(Numeric(10, 4))

    __table_args__ = (
        Index('idx_polymarket_orderbook_market', 'market_id', 'time'),
    )


# ==========================================
# Trading Signals & Orders
# ==========================================

class Signal(Base):
    """Trading signals generated by the strategy."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_id = Column(String(100), ForeignKey('markets.market_id'), nullable=False, index=True)
    signal_time = Column(DateTime(timezone=True), nullable=False)
    minutes_since_open = Column(Integer)

    # Spot price analysis
    spot_price_start = Column(Numeric(20, 8))
    spot_price_current = Column(Numeric(20, 8))
    price_change_pct = Column(Numeric(10, 6))
    momentum_score = Column(Numeric(10, 6))  # R² consistency score

    # Polymarket pricing
    pm_yes_price = Column(Numeric(10, 4))
    pm_no_price = Column(Numeric(10, 4))

    # Signal decision
    recommended_outcome = Column(String(10))  # 'YES', 'NO', 'NONE'
    confidence_score = Column(Numeric(10, 6))
    expected_value = Column(Numeric(10, 6))

    # Execution
    executed = Column(Boolean, default=False, index=True)
    execution_reason = Column(Text)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    market = relationship("Market", back_populates="signals")
    orders = relationship("Order", back_populates="signal")


class Order(Base):
    """All orders placed on Polymarket."""

    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(String(100), unique=True)
    market_id = Column(String(100), ForeignKey('markets.market_id'), nullable=False)
    signal_id = Column(Integer, ForeignKey('signals.id'))

    order_type = Column(String(20))  # 'MARKET', 'LIMIT'
    side = Column(String(10))  # 'BUY', 'SELL'
    outcome = Column(String(10))  # 'YES', 'NO'

    quantity = Column(Numeric(20, 2))
    price = Column(Numeric(10, 4))

    status = Column(String(20), index=True)  # 'pending', 'filled', 'cancelled', 'failed'

    placed_at = Column(DateTime(timezone=True), nullable=False)
    filled_at = Column(DateTime(timezone=True))
    cancelled_at = Column(DateTime(timezone=True))

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    market = relationship("Market", back_populates="orders")
    signal = relationship("Signal", back_populates="orders")
    trades = relationship("Trade", back_populates="order")


class Trade(Base):
    """Filled orders (executed trades)."""

    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    trade_id = Column(String(100), unique=True)
    order_id = Column(String(100), ForeignKey('orders.order_id'))
    market_id = Column(String(100), ForeignKey('markets.market_id'), nullable=False)

    outcome = Column(String(10))
    quantity = Column(Numeric(20, 2))
    avg_price = Column(Numeric(10, 4))
    cost = Column(Numeric(20, 2))
    fee = Column(Numeric(20, 2))

    filled_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    order = relationship("Order", back_populates="trades")
    market = relationship("Market", back_populates="trades")
    positions = relationship("Position", back_populates="trade")


# ==========================================
# Positions & Account Management
# ==========================================

class Position(Base):
    """Open and closed positions."""

    __tablename__ = "positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_id = Column(String(100), ForeignKey('markets.market_id'), nullable=False)
    trade_id = Column(String(100), ForeignKey('trades.trade_id'))

    outcome = Column(String(10))
    quantity = Column(Numeric(20, 2))
    avg_entry_price = Column(Numeric(10, 4))
    cost_basis = Column(Numeric(20, 2))

    status = Column(String(20), index=True)  # 'open', 'resolved'

    # Resolution
    resolution_outcome = Column(String(10))
    payout = Column(Numeric(20, 2))
    realized_pnl = Column(Numeric(20, 2))

    opened_at = Column(DateTime(timezone=True), nullable=False)
    closed_at = Column(DateTime(timezone=True))

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    market = relationship("Market", back_populates="positions")
    trade = relationship("Trade", back_populates="positions")


class AccountBalance(Base):
    """Account balance history (time-series)."""

    __tablename__ = "account_balance"

    time = Column(DateTime(timezone=True), primary_key=True)
    balance = Column(Numeric(20, 2), nullable=False)
    equity = Column(Numeric(20, 2))  # Including open positions
    available = Column(Numeric(20, 2))


# ==========================================
# System Events & Metrics
# ==========================================

class SystemEvent(Base):
    """System logs and events."""

    __tablename__ = "system_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    event_time = Column(DateTime(timezone=True), nullable=False)
    event_type = Column(String(50), index=True)  # 'error', 'warning', 'info'
    component = Column(String(50))  # 'market_discovery', 'price_monitor', etc.
    message = Column(Text)
    metadata = Column(JSONB)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class PerformanceMetric(Base):
    """Daily performance summary."""

    __tablename__ = "performance_metrics"

    date = Column(Date, primary_key=True)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Numeric(10, 4))
    total_pnl = Column(Numeric(20, 2))
    avg_trade_pnl = Column(Numeric(20, 2))
    max_drawdown = Column(Numeric(20, 2))
    sharpe_ratio = Column(Numeric(10, 4))


# ==========================================
# Helper Functions
# ==========================================

def create_all_tables(engine):
    """Create all tables in the database."""
    Base.metadata.create_all(engine)


def drop_all_tables(engine):
    """Drop all tables (use with caution!)."""
    Base.metadata.drop_all(engine)
